### ISSUE TITLE
Feature: multiple GMs

### ISSUE THREAD

**Issue by SGMartin** [Darkr4ptor/mv_mafia_bot#9]
This has been requested a lot. For complex games, a second GM is often designated to keep the game moving in case the main GM is absent. At this moment, only a single GM is accepted by the bot. 

Adding a second or even a third GM implies deep changes to how the bot handles the start and the end of the day, but it should be straightforward to allow a second player (sub GM) to perform vote count requests or other minor tasks.

**Comment by Darkr4ptor** [comment]
Fixed in #12
